spring: 
 profiles:
  active:
  - dev
---
server: 
 port: 7001
spring: 
 profiles: dev
 application: 
  name: micro-service-springcloud-config-eureka-client
eureka: 
 instance: 
  hostname: eureka7001.com
  client: 
  register-with-eureka: false
  fetch-registry: false #不通过eureka获取注册信息
  service-url: 
   defaultZone: http://eureka.com:7001/eureka/
---
server: 
 port: 7001
spring: 
 profiles: dev
 application: 
  name: micro-service-springcloud-config-eureka-client
eureka: 
 instance: 
  hostname: eureka7001.com
  client: 
  register-with-eureka: false
  fetch-registry: false #不通过eureka获取注册信息
  service-url: 
   defaultZone: http://eureka.com:7001/eureka/