spring: 
 profiles:
  active:
  - dev
---
server: 
 port: 8201
spring: 
 profiles: 
 application: 
  name: micro-service-springcloud-config-client
eureka: 
 client: 
  service-url: 
   defaultZone: http://eureka-dev.com:7001/eureka/
---